data_creating:
  border_size: 6.0
  img_num: 100000
  img_size: 64
  square_size: 17
data_path: dataset
model_class:
  hidden_count: 1
  hidden_size: 128
  input_size: 4096
  output_size: 2
random_split:
  test: 0.2
  train: 0.7
  val: 0.1
save_load:
  best_params_file_name: best_params_dict.pt
  current_params_file_name: current_params_dict.pt
  load_mode:
    load_best: None
    load_to_continue: None
  threshold: 0.0001
saved_params_path: saved_params
train:
  epoch_num: 1
  epochs_on_plateau_allow: 10
  learning_rate: 0.001
  lr_scheduler:
    factor: 0.1
    mode: min
    patience: 5
train_or_predict: predict
