data_path: 'dataset'
random_split:
  train: 0.7
  val: 0.1
  test: 0.2
data_creating:
  img_num: 100000
  img_size: 64
  square_size: 17
  border_size: 5
model_class:
  input_size: 4096
  output_size: 2
  hidden_size: 128
  hidden_count: 1
train:
  epoch_num: 100
  learning_rate: 0.0001